
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Originarios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contato
{

    public int id_ctt { get; set; }

    public string nome { get; set; }

    public string email { get; set; }

    public string endereco { get; set; }

    public string assunto { get; set; }

    public string mensagem { get; set; }

}

}
