

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Originarios.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OriginariosEntities : DbContext
{
    public OriginariosEntities()
        : base("name=OriginariosEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Postagem> Postagem { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Contato> Contato { get; set; }

    public virtual DbSet<Publicacao> Publicacao { get; set; }

}

}

