
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Originarios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Publicacao
{

    public int id_public { get; set; }

    public int usuario { get; set; }

    public string titulo { get; set; }

    public string corpo { get; set; }

    public string locali { get; set; }

    public string data_public { get; set; }



    public virtual Usuario Usuario1 { get; set; }

}

}
